name: Update bar-data.json

on:
  workflow_dispatch:
  schedule:
    # Every 10 minutes between 03:00–10:59 UTC Mon–Fri (≈ 08:30–16:29 IST)
    - cron: "*/10 3-10 * * 1-5"

permissions:
  contents: write

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install (nothing to install)
        run: echo "No deps"

      - name: Run updater
        run: npm run update

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add bar-data.json
          git diff --quiet && echo "No changes" || git commit -m "chore: update bar-data.json [skip ci]"
          git push
